from .weird_prompt_add import (
    NODE_CLASS_MAPPINGS as PROMPT_ADD_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_ADD_DISPLAY_NAME_MAPPINGS,
)
from .weird_prompt_node import (
    NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_NAME_MAPPINGS,
)
from .weird_text_node import (
    NODE_CLASS_MAPPINGS as TEXT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {
    **TEXT_CLASS_MAPPINGS,
    **PROMPT_CLASS_MAPPINGS,
    **PROMPT_ADD_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **TEXT_DISPLAY_NAME_MAPPINGS,
    **PROMPT_DISPLAY_NAME_MAPPINGS,
    **PROMPT_ADD_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
